In [1]:
import numpy as np
from sklearn import datasets
import random

In [2]:
iris = datasets.load_iris()
data = iris.data
target = iris.target
#data

In [3]:
#centroids = np.array((random.sample(list(data),3)))
centroids = np.random.rand(3,4)
centroids

array([[0.0144444 , 0.06042934, 0.98332797, 0.36729436],
       [0.89727717, 0.35383684, 0.27782879, 0.65908892],
       [0.32052593, 0.06736352, 0.79094492, 0.94982577]])

In [4]:
from scipy.spatial import distance

dist = distance.cdist(data,centroids,'euclidean')

dist

array([[ 6.15590164,  5.38806576,  5.96318307],
       [ 5.71938215,  4.94914138,  5.5231446 ],
       [ 5.6515134 ,  4.88026047,  5.4602729 ],
       [ 5.5282228 ,  4.79124551,  5.34563187],
       [ 6.13073634,  5.37028311,  5.94223736],
       [ 6.65290917,  5.91096304,  6.45126722],
       [ 5.68842653,  4.93735551,  5.49668862],
       [ 6.02523312,  5.27407904,  5.83686056],
       [ 5.24384043,  4.49689281,  5.05955777],
       [ 5.7832551 ,  5.03681298,  5.602984  ],
       [ 6.52270044,  5.75984252,  6.32946304],
       [ 5.87048093,  5.14482797,  5.69113017],
       [ 5.63805639,  4.87906483,  5.45519904],
       [ 5.20500923,  4.42371428,  5.02536461],
       [ 7.00484152,  6.19615682,  6.79851679],
       [ 7.17115302,  6.40300027,  6.9653103 ],
       [ 6.62177188,  5.82767081,  6.40715262],
       [ 6.15399595,  5.3804679 ,  5.95143572],
       [ 6.84310445,  6.09045999,  6.64228658],
       [ 6.33393582,  5.58225465,  6.14011238],
       [ 6.37954132,  5.63799224,  6.188

In [5]:
MemberShip = []

for i in range(len(dist)):
    
    if dist[i][0]==0:
        dist[i][0] = dist[i][0] + 0.01
        MemberShip = np.append(MemberShip,(1/dist[i][0])/1/np.sum(dist[i]))
    else:
        MemberShip = np.append(MemberShip,(1/dist[i][0])/1/np.sum(dist[i]))
        
    if dist[i][1]==0:
        dist[i][1] = dist[i][1] + 0.01
        MemberShip = np.append(MemberShip,(1/dist[i][1])/1/np.sum(dist[i]))
    else:
        MemberShip = np.append(MemberShip,(1/dist[i][1])/1/np.sum(dist[i]))
        
        
    if dist[i][2]==0:
        dist[i][2] = dist[i][2] + 0.01
        MemberShip = np.append(MemberShip,(1/dist[i][2])/1/np.sum(dist[i]))
    else:
        MemberShip = np.append(MemberShip,(1/dist[i][2])/1/np.sum(dist[i]))

In [6]:
MemberShip = np.reshape(MemberShip,(-3,3))

In [7]:
centroid = []
for i in range(len(centroids)):
    centroid = np.append(centroid,np.matmul(np.transpose(MemberShip[:,i]),data)/sum(MemberShip[:,i]),axis=0)


print(centroids)
np.reshape(centroid,(-4,4))

[[0.0144444  0.06042934 0.98332797 0.36729436]
 [0.89727717 0.35383684 0.27782879 0.65908892]
 [0.32052593 0.06736352 0.79094492 0.94982577]]


array([[5.56542934, 3.07180605, 3.18582749, 0.95819318],
       [5.53774405, 3.07935014, 3.11576779, 0.92905983],
       [5.56278377, 3.07170796, 3.18060696, 0.95626955]])

In [13]:
while True:
    dist = distance.cdist(data,centroids,'euclidean')

    MemberShip = []

    for i in range(len(dist)):

        if dist[i][0]==0:
            dist[i][0] = dist[i][0] + 1
            MemberShip = np.append(MemberShip,(1/dist[i][0])/1/np.sum(dist[i]))
        else:
            MemberShip = np.append(MemberShip,(1/dist[i][0])/1/np.sum(dist[i]))

        if dist[i][1]==0:
            dist[i][1] = dist[i][1] + 1
            MemberShip = np.append(MemberShip,(1/dist[i][1])/1/np.sum(dist[i]))
        else:
            MemberShip = np.append(MemberShip,(1/dist[i][1])/1/np.sum(dist[i]))


        if dist[i][2]==0:
            dist[i][2] = dist[i][2] + 1
            MemberShip = np.append(MemberShip,(1/dist[i][2])/1/np.sum(dist[i]))
        else:
            MemberShip = np.append(MemberShip,(1/dist[i][2])/1/np.sum(dist[i]))


    MemberShip = np.reshape(MemberShip,(-3,3))
    print(dist)

    centroid = []
    for i in range(len(centroids)):
        centroid = np.append(centroid,np.matmul(np.transpose(MemberShip[:,i]),data)/sum(MemberShip[:,i]),axis=0)


    centroid  = np.reshape(centroid,(-4,4))
    if np.allclose(centroids,centroid):
        centroids = centroid
        break
    else:
        centroids = centroid
    

[[3.53128872e+00 3.53128872e+00 3.53128872e+00]
 [3.53836120e+00 3.53836120e+00 3.53836120e+00]
 [3.70270172e+00 3.70270172e+00 3.70270172e+00]
 [3.56230263e+00 3.56230263e+00 3.56230263e+00]
 [3.57631095e+00 3.57631095e+00 3.57631095e+00]
 [3.22645316e+00 3.22645316e+00 3.22645316e+00]
 [3.64142829e+00 3.64142829e+00 3.64142829e+00]
 [3.45543051e+00 3.45543051e+00 3.45543051e+00]
 [3.72290209e+00 3.72290209e+00 3.72290209e+00]
 [3.49428104e+00 3.49428104e+00 3.49428104e+00]
 [3.41906420e+00 3.41906420e+00 3.41906420e+00]
 [3.43365694e+00 3.43365694e+00 3.43365694e+00]
 [3.60832371e+00 3.60832371e+00 3.60832371e+00]
 [4.05215992e+00 4.05215992e+00 4.05215992e+00]
 [3.71887080e+00 3.71887080e+00 3.71887080e+00]
 [3.54259792e+00 3.54259792e+00 3.54259792e+00]
 [3.57910603e+00 3.57910603e+00 3.57910603e+00]
 [3.49571166e+00 3.49571166e+00 3.49571166e+00]
 [3.19061123e+00 3.19061123e+00 3.19061123e+00]
 [3.47275107e+00 3.47275107e+00 3.47275107e+00]
 [3.18433667e+00 3.18433667e+00 3.184336

In [9]:
centroids

array([[6. , 2.9, 4.5, 1.5],
       [6. , 2.9, 4.5, 1.5],
       [6. , 2.9, 4.5, 1.5]])

In [10]:
recalculate = distance.cdist(data,centroids)
recalculate

array([[3.53128872e+00, 3.53128872e+00, 3.53128872e+00],
       [3.53836120e+00, 3.53836120e+00, 3.53836120e+00],
       [3.70270172e+00, 3.70270172e+00, 3.70270172e+00],
       [3.56230263e+00, 3.56230263e+00, 3.56230263e+00],
       [3.57631095e+00, 3.57631095e+00, 3.57631095e+00],
       [3.22645316e+00, 3.22645316e+00, 3.22645316e+00],
       [3.64142829e+00, 3.64142829e+00, 3.64142829e+00],
       [3.45543051e+00, 3.45543051e+00, 3.45543051e+00],
       [3.72290209e+00, 3.72290209e+00, 3.72290209e+00],
       [3.49428104e+00, 3.49428104e+00, 3.49428104e+00],
       [3.41906420e+00, 3.41906420e+00, 3.41906420e+00],
       [3.43365694e+00, 3.43365694e+00, 3.43365694e+00],
       [3.60832371e+00, 3.60832371e+00, 3.60832371e+00],
       [4.05215992e+00, 4.05215992e+00, 4.05215992e+00],
       [3.71887080e+00, 3.71887080e+00, 3.71887080e+00],
       [3.54259792e+00, 3.54259792e+00, 3.54259792e+00],
       [3.57910603e+00, 3.57910603e+00, 3.57910603e+00],
       [3.49571166e+00, 3.49571

In [11]:
predict_target = []

for i in range(len(recalculate)):
    predict_target = np.append(predict_target,np.argmax(recalculate[i]))
    

predict_target

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0.,
       1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [130]:
membership = np.random.rand(3,3)
membership/np.linalg.norm(membership)
sum(membership[0])

1.8381343483059824